name = "NowcastingRepl"
uuid = "7cb8100d-3f76-49f0-b91d-514678cac1f5"
authors = ["Valerio Palagi", "Isotta Valpreda"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
